apiVersion: v2
appVersion: "3.1"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.9.13
description: The Cloud-Native Ingress and API-management
home: https://konghq.com/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/41f61373-31fb-43fd-b9a8-42dc7fca59cb.png
kubeVersion: '>= 1.22.0-x'
maintainers:
- email: harry@konghq.com
  name: hbagdi
- email: traines@konghq.com
  name: rainest
name: kong
sources:
- https://github.com/Kong/charts/tree/main/charts/kong
version: 2.16.5
