annotations:
  artifacthub.io/changes: "- ⬆️i Update Traefik appVersion to 2.9.5\n- \U0001F41B
    Use static appVersion for testing container config\n"
apiVersion: v2
appVersion: v2.9.5
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/84303761-3ea2-4cf9-908f-01f39166c24c.png
keywords:
- traefik
- ingress
maintainers:
- email: emile@vauge.com
  name: emilevauge
- email: daniel.tomcej@gmail.com
  name: dtomcej
- email: ldez@traefik.io
  name: ldez
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: charlie.haley@traefik.io
  name: charlie-haley
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
type: application
version: 20.5.2
