apiVersion: v1
appVersion: 14.10.2
description: Web-based Git-repository manager with wiki and issue-tracking features.
home: https://about.gitlab.cn/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/4c415edc-64eb-4faf-b132-83a288bce2f1.png
keywords:
- gitlab
maintainers:
- email: support@gitlab.cn
  name: JiHu(GitLab)
name: gitlab
sources:
- https://jihulab.com/gitlab-cn/charts/gitlab
version: 5.10.2
