apiVersion: v2
appVersion: elastic-jupyter-operator-0.1.1
description: A Helm chart for elastic Jupyter notebooks
home: https://github.com/tkestack/charts
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/5dfdd40c-19fe-4274-a1f4-5770a2d49e0d.svg
keywords:
- kubeflow
- training
maintainers:
- email: lucaswzhang@tencent.com
  name: lucaswzhang
- email: cegao@tencent.com
  name: cegao
name: elastic-jupyter-operator
version: 0.1.1
kubeVersion: ">=1.16.0-x"
