apiVersion: v1
appVersion: 2.5.0
description: Apache Kafka is a distributed streaming platform.
home: https://kafka.apache.org/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/f7720191-fda7-498c-847e-30f055767fa6.png
keywords:
- kafka
- zookeeper
- streaming
- producer
- consumer
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: kafka
sources:
- https://github.com/bitnami/bitnami-docker-kafka
version: 11.0.0
