apiVersion: v1
appVersion: 2.24.0
description: OpenID Connect Identity (OIDC) and OAuth 2.0 Provider with Pluggable Connectors
home: https://github.com/dexidp/dex/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/d71c6705-05b3-401e-bddf-d1c42110c208.png
keywords:
- dex
- oidc
maintainers:
- email: Kevin.Fox@pnnl.gov
  name: kfox1111
- email: shane.starcher@gmail.com
  name: sstarcher
- email: pete.brown@powerhrg.com
  name: rendhalver
- email: vi7alya@gmail.com
  name: vi7
name: dex
version: 2.13.0
