apiVersion: v2
appVersion: 7.5.5
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: https://cloudcache.tencent-cloud.com/qcloud/ui/static/Industry_tke/e36ebf5a-40e6-422f-9ee0-b4fa29ab9cb3.png
maintainers:
- email: zanhsieh@gmail.com
  name: zanhsieh
- email: rluckie@cisco.com
  name: rtluckie
- email: maor.friedman@redhat.com
  name: maorfr
- email: miroslav.hadzhiev@gmail.com
  name: Xtigyro
- email: mail@torstenwalter.de
  name: torstenwalter
name: grafana
sources:
- https://github.com/grafana/grafana
type: application
version: 6.10.0
